name: CI

on:
  push:
    branches:
      - main  # Replace with your default branch name if different
  pull_request:
    branches:
      - main  # Triggers on pull requests targeting the main branch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']  # Specify Python versions to test against

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .

    - name: Run code format check (Black)
      run: black --check subprocess_execution/ tests/

    - name: Run import sorting check (isort)
      run: isort --check-only subprocess_execution/ tests/

    - name: Run linting (Flake8)
      run: flake8 subprocess_execution/ tests/

    - name: Run type checks (mypy)
      run: mypy subprocess_execution/

    - name: Run tests (pytest)
      run: pytest

